### ISSUE TITLE
Possible duplicate export template installation

### ISSUE THREAD

**Issue by Calinou** [josephbmanley/build-godot-action#8]
Forgive me if I'm missing something, but I noticed [`entrypoint.sh` downloads and installs export templates](https://github.com/josephbmanley/build-godot-action/blob/master/entrypoint.sh#L4-L11) even though [the base image also installs them](https://github.com/aBARICHELLO/godot-ci/blob/master/Dockerfile#L16-L25). This could unnecessarily slow down actions.

**Comment by yeslayla** [comment]
Hello! Thanks for the interest in this action! :smile: 

The export templates have to be installed in the user's home directory. The GitHub action's user is different from the one in the base image. Because of that, the action currently does template installation at runtime.

Though, I believe it would be possible to decrease build times for matrix builds by having it in the build action step. Also since the templates are already on the image, but with the wrong dir a move could be done instead of a download. I'll add both of those to my _todo_.

**Comment by yeslayla** [comment]
Correction: not user, home directory

**Comment by Tadaboody** [comment]
How about copying/ moving it to the right directory in your docker file?
